export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Quotes} from './Quotes'
export {default as Dashboard} from './Dashboard'
